/**
 * Reads src/tokens/tokens.json and writes src/styles/generated-token-vars.css
 * so CSS custom properties stay the single runtime reflection of token values.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const tokensPath = join(root, "src/tokens/tokens.json");
const outPath = join(root, "src/styles/generated-token-vars.css");

/** @param {string[]} parts */
function toCssVarName(parts) {
  const [head, ...tail] = parts;
  if (head === "color") {
    return `--color-${tail.join("-")}`;
  }
  if (head === "typography") {
    const [category, ...rest] = tail;
    if (category === "fontFamily") return `--font-family-${rest.join("-")}`;
    if (category === "fontSize") return `--font-size-${rest.join("-")}`;
    if (category === "lineHeight") return `--line-height-${rest.join("-")}`;
    if (category === "fontWeight") return `--font-weight-${rest.join("-")}`;
    return `--typography-${tail.join("-")}`;
  }
  if (head === "spacing") {
    const sanitized = tail
      .map((segment) => segment.replace(/\./g, "-"))
      .join("-");
    return `--spacing-${sanitized}`;
  }
  if (head === "radius") {
    return `--radius-${tail.join("-")}`;
  }
  if (head === "shadow") {
    return `--shadow-${tail.join("-")}`;
  }
  return `--${parts.join("-")}`;
}

/**
 * @param {unknown} value
 * @param {string[]} parts
 * @param {Record<string, string>} out
 */
function walk(value, parts, out) {
  if (value === null || value === undefined) return;
  if (typeof value === "object" && !Array.isArray(value)) {
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith("_")) continue;
      walk(child, [...parts, key], out);
    }
    return;
  }
  if (typeof value === "string" || typeof value === "number") {
    const name = toCssVarName(parts);
    out[name] = String(value);
  }
}

const raw = readFileSync(tokensPath, "utf8");
/** @type {unknown} */
const tokens = JSON.parse(raw);
const vars = {};
walk(tokens, [], vars);

const header = `/* AUTO-GENERATED by scripts/sync-tokens.mjs — do not edit by hand */\n`;
const lines = Object.entries(vars)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, v]) => `  ${k}: ${v};`);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `${header}:root {\n${lines.join("\n")}\n}\n`,
  "utf8",
);

console.log(`Wrote ${Object.keys(vars).length} CSS variables to ${outPath}`);
